MODEL:
  VID:
    ENABLE: True
  RPN:
    ANCHOR_SIZES: (64, 128, 256, 512)
    PRE_NMS_TOP_N_TRAIN: 6000
    PRE_NMS_TOP_N_TEST: 6000
    POST_NMS_TOP_N_TRAIN: 300
    POST_NMS_TOP_N_TEST: 300
  ROI_HEADS:
    BATCH_SIZE_PER_IMAGE: 128
    SCORE_THRESH: 0.001
    NMS: 0.5
    DETECTIONS_PER_IMG: 300
  ROI_BOX_HEAD:
    NUM_CLASSES: 31
    POOLER_RESOLUTION: 7
  RESNETS:
    RES5_DILATION: 2
INPUT:
  MIN_SIZE_TRAIN: (600,)
  MAX_SIZE_TRAIN: 1000
  MIN_SIZE_TEST: 600
  MAX_SIZE_TEST: 1000
DATASETS:
  TRAIN: ("DET_train_30classes", "VID_train_15frames")
  TEST: ("VID_val_frames",)
SOLVER:
  BASE_LR: 0.002
  WEIGHT_DECAY: 0.0001
  STEPS: (40000, )
  MAX_ITER: 60000
  IMS_PER_BATCH: 8
  WARMUP_ITERS: 500
TEST:
  IMS_PER_BATCH: 8
  DETECTIONS_PER_IMG: 300