MODEL:
  VID:
    METHOD: "mega"
    ROI_BOX_HEAD:
      ATTENTION:
        ENABLE: True
        STAGE: 3
  META_ARCHITECTURE: "GeneralizedRCNNMEGA"
  WEIGHT: "catalog://ImageNetPretrained/MSRA/R-101"
  BACKBONE:
    CONV_BODY: "R-101-C4"
  ROI_BOX_HEAD:
    FEATURE_EXTRACTOR: "MEGAFeatureExtractor"
    PREDICTOR: "FPNPredictor"
DATASETS:
  TRAIN: ("COCO_train_34classes", "COCO_valmini_34classes","VidORtrain_freq32")
  # 58890 + 25407 + 226781 = 311078, 31w
  TEST: ("VidORval_freq2",)
SOLVER:
  BASE_LR: 0.001
  WEIGHT_DECAY: 0.0001
  STEPS: (100000, )
  MAX_ITER: 150000
  IMS_PER_BATCH: 2    # this config file uses 2 GPUs
  WARMUP_ITERS: 500
TEST:
  IMS_PER_BATCH: 2
  DETECTIONS_PER_IMG: 300